---
git:
  depth: 1

notifications:
  email: false
  webhooks:
    urls:
    - https://ensemble.engineyard.com/travis
    on_success: always
    on_failure: always
    on_start: true

before_script:
  - echo "--profile --color" > '.rspec' # Report slowest ten tests, make it pretty

script: bundle exec rake

env:
  global:
  - RUBY_GC_MALLOC_LIMIT=1000000000
  - RUBY_HEAP_SLOTS_GROWTH_FACTOR=1.25
  - RUBY_HEAP_MIN_SLOTS=800000
  - RUBY_FREE_MIN=600000