#!/usr/bin/env bash
set -x
set -e

env

case "$1" in
"internal")
   echo "running internal tests"
   export REDIS_URL=redis://$REDIS_URL
   export BUNDLE_GEMFILE=EYIntegratedGemfile
   ;;
"public")
   echo "running public tests"
   ;;
*)
   echo "unknown unit $1"
   exit 1
   ;;
esac

gem install bundler --no-rdoc --no-ri
time bundle install
time bundle exec rake

echo
echo "Complete"
